title: Michael Christen
description: Computer Engineering and Personal Writings

url: http://karatekid.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Travel
   url: /travel

social:
   github: karatekid
   twitter: 
   facebook: michael.d.christen
   email: mchristen96@gmail.com

disqus: karatekid-github
google_analytics: "UA-60635422-1"
